### PR TITLE
_sendMail should return the promise

### PR DESCRIPTION
**Pull request by dan-nyanko**
fixes issue #2

### CODE REVIEW

**Comment by sebsylvester** [comment]
Hi, thanks for the PR. I haven't used the adapter directly from Cloud code, so it's cool you pointed this out.

**Comment by dbake** [comment]
@dan-nyanko  How are you using this in Cloud Code? I am trying to configure, but am getting this error

TypeError: Cannot read property 'get' of undefined

At the following line: 

const MailgunAdapter = AppCache.get(process.env.APP_ID)['userController']['adapter'];

I checked the lined above: 

const AppCache = require('parse-server/lib/cache').AppCache;
console.log(AppCache);

And AppCache is undefined. What am I doing wrong?

**Comment by sebsylvester** [comment]
Sorry, I'm not able to reproduce the error.
Is AppCache the only dependency you are having trouble with from Cloud Code?
If so, you could try reach out to the file manually, like this: 
const AppCache = require('../path/to/node_modules/parse-server/lib/cache').AppCache;

**Comment by sebsylvester** [comment]
I forgot to ask. How are you running Parse Server, as an express module or standalone?
I never use the standalone version, so I don't test for it.

**Comment by dan-nyanko** [comment]
@dbake - check out [`example-parse-server`](https://github.com/dan-nyanko/example-parse-server).

`const adapter = AppCache.get(settings.appId)['userController']['adapter'];` belongs within the `Parse.Cloud.define( ...` method body and not at the top of your file with your other imports. This parse-server time to boot, setup cloud code and the email adapter.

**Pull request merged**
