### PR TITLE
Replace lodash.templates with Handlebars

### PR DESCRIPTION
**Pull request by peterpme**
Hey again,

After digging around, I found the answer to #22 and realized what you're doing is very similar to Handlebars itself.

Handlebars also uses curly braces `{{ }}` but offers several helpers that can help make a user's life easier, like `{{#each}}`.

### CODE REVIEW

**Comment by sebsylvester** [comment]
Hi, thanks for the pull request. 
I do have some thoughts about replacing lodash.template with handlebars. 
I've installed handlebars in an empty project and noticed it adds a whopping 22 packages to your project. For the little value it adds to the module (nobody requested a similar feature before), it's not worth all that extra weight. On the other hand, I could accomplish the same thing by adding mustache, which does not have any dependencies at all. Mustache will also allow you loop over data in your template. So I will put it on my schedule to try it out, and do some live testing.

**Comment by sebsylvester** [comment]
Hi, just wanted to let you know that I've replaced ```lodash.template``` with ```mustache```, so that iterating over collections inside template code is now possible.

**Comment by peterpme** [comment]
Awesome, you rock!

Here's some food for thought:

FWIW your package includes 507 top-level modules and 1551 modules altogether using Yarn, the optimized npm package manager:

507:
```yarn list --depth=0 | wc -l``` 

1551
```yarn lit | wc -l```

Handlebars pre-compiled comes out to 18kb which is twice the size of mustache, but there's a reason for that and I highly recommend you look past the surface level details, especially since this is a server-side module 😄

Obviously this is your package so you can do as you please! I'm going to put up a handlebars version for the folks looking for the extra features handlebars adds!

Thanks again for putting this together, I'd never be able to get as far as I have without you!

**Comment by sebsylvester** [comment]
Hi,
that number you presented is a bit skewed don't you think? Given that the parse-server dependency is only needed to access the MailAdapter constructor for inheritance purposes. Perhaps it's not a bad idea to get rid of the parse-server dep altogether and just maintain a copy of that class somewhere in parse-server-mailgun. What do you think?

**Comment by peterpme** [comment]
I think it's a great idea. If you can get rid of it without it becoming too big of a hassle, I'd recommend it.

I'm still getting myself acquainted with Parse & Parse modules but I'd be happy to help too :)

You can also try something like rollup which is an ES6-aware minifier that will compile down only the necessities.

**Pull request closed without merging**
