### PR TITLE
Add field 'extra' to option, which allows add any other mailcomposer fields like attachments etc

### PR DESCRIPTION
**Pull request by fduch2k**

### CODE REVIEW

**Comment by sebsylvester** [comment]
Hello,
Can you explain how the "extra" option translates to the inclusion of an attachment?
The mailcomposer docs have been removed. The page now refers you to nodemailer?? And the mailcomposer source only mentions an "attachment" option.

**Comment by fduch2k** [comment]
Extra can contains any of mailcomposer email fields, such as bcc, cc, attachments, headers etc. Docs is here https://nodemailer.com/extras/mailcomposer/ I'll fix failed tests

**Comment by fduch2k** [comment]
Thank you for merging. Should I make merge request for fixed test?

**Comment by sebsylvester** [comment]
That would be nice

**Pull request merged**
